### ISSUE TITLE
Advance algorithm broken in 0.82

### ISSUE THREAD

**Issue by llluis** [repetier/Repetier-Firmware#107]
I was using the advance algorithm feature, including the quadratic term, since 0.80 (dev) successfully. However since 0.82, the feature is broken for me. I tough that it was a problem with my setup (motors, configuration, electronics, etc), however, I switched back to 0.81 today and everything is working again, with the same parameters.
The quadratic term can be observed during infill, in direction changes, as the extruder reverts the movement briefly. In 0.82, this didn't happen and suddenly, during a print, the extruder goes nuts, turning fast both ways and then continues. Sometimes just a stall is heard.

I don't know what kind of information I can provide to help you track this down, but, just let me know and I will send it.

Some initial information:
- Filament: 3mm
- Wades geared extruder
- 0.35mm JHead
- ABS
- Extr. 603 steps/mm (16x microstepping)
- Extr. Max Acc 3000
- Extr. Max Feed 50
- Extr. Start Feed 10
- Advance K factor 40
- Advance L factor 30

Thanks in advance.
Regards

**Comment by 0x4d0x44** [comment]
It looks like advance is still not functional. I have a direct drive extruder mounted on the X carriage directly on the hot end. I've tried several combination of linear and quadratic advance values, from very small to ridiculously high values (up to hundreds), but I can't spot any differences in prints.
I carefully tuned esteps, but I continue to have a severe over-extrusion at direction change. This is particularly visible in the top layer infill. I'm working with low acceleration (600) and jerk (10) because of my printer's mechanic. It seems like the deceleration phase at the end of a segment is not reflected in the extruder, even with the advance turned on.

**Comment by Nandox7** [comment]
I could fix those issues with over-extruding in corners by increasing Jerk.
In my case from 10 to ~20, now I get some nice sharper corners.
