### ISSUE TITLE
Z axis movement always against gravity

### ISSUE THREAD

**Issue by Huwyler** [repetier/Repetier-Firmware#139]
I have an Eventorbot, which does the Z movement by moving the bed down (as many printers do).
I noticed that the movement sometimes lags a bit. That's because if it's going down, there is no "rigid connection" pulling the bed down. It's only a) gravity and b) some sort of spring (I don't know the english term for it) between the motor and the threaded rod. 

Kisslicer has a nice option that makes the bed go down - say - 0.5mm and then come up again 0.35mm, which results in a layer thickness of 0.15mm. If the bed lags while going down, that's no problem, as long as it went down at least 0.15mm. By going up 0.35mm, the "rigidity" of the system is then re-gained. 
It's something like backlash compensation, but not quite the same.

It would be cool, if Repetier could do this on its own, because not all slicers offer this cool feature.

**Comment by tiwanacote** [comment]
Hi! The post is very old, but I would know if the this feature was implemented in new versions, Any news?

The problem is: If backlash exist into UP_to_DOWN beds and linear bearings are a little stuck or locked, when Z motor rotate to increase its position, the build plate stay still (No gravity action) and extruder could crash with printed part loosing steps in X and Y or over-extrude in the same Z plane. 

Thank you!!

**Comment by repetier** [comment]
No, this is not implemented in firmware. There seems no demand on this as I never heard about this problem for 2 years. However, it is easy to incorporate the trick into a slicer in the before layer change code. Just switch to relative mode and move down 0.5mm and go back in absolute mode. Then the next z move will go in opposite direction.
