### ISSUE TITLE
Advance algorithm noisy on delta printers

### ISSUE THREAD

**Issue by presslab-us** [repetier/Repetier-Firmware#342]
This relates to branch work092 on a mega2560.  I am using the linear advance algorithm on my delta printer with a long Bowden and 1.75mm filament.  I have the coefficient set to 600 now and could probably use a bit more.  I know this is a large number due to the long Bowden, and this will only amplify the noise problem.

My problem is that the extruder motor makes all sorts of pops, clicks, groans, etc.  Even during a straight or round move where velocity should be constant I can hear it popping with a regular period.

To address this I have added a simple 16 sample boxcar filter to the calculated "tred" in the "updateAdvanceSteps" function; since advanceL is constant (for the move) the noise is coming from the velocity.  This greatly improves things but introduces a few other problems, and probably isn't the right way to do it.  However with this filter I can use the advance algorithm without my extruder motor sounding like it's disintegrating.  And with the algorithm, the prints are looking much better!

Is it expected that the velocity with a delta printer is noisy?  Do you have any ideas for things I can try to reduce the source of the noise?  Should I use an IIR filter instead of a boxcar?

**Comment by qx1147** [comment]
This looks weird to me (work092/extruder.cpp/line469):
`if(Printer::maxExtruderSpeed > 15) Printer::maxExtruderSpeed = 15;`

Shouldn't it be "< 15"? "maxExtruderSpeed " will be used as interval for the extruder stepper interrupt, so low value means fast. Obviously, a low value not only means high stepping rates (if there is more than one step in the queue due to advance) but also increased chances of having intermittent step reversals (as positive bresenham steps are more likely executed before having had a chance to be possibly cancelled by negative advance steps, so at least part of the averaging between positive and negative steps is done in the motor - not good).
Unfortunately, this won't fix the (IMHO) inherently flawed "advance" implementation entirely, but fixing the implementation seems kind of impossible without turning the whole planning algorithm / stepper control upside down. We save that for another day.

**Comment by repetier** [comment]
No, > 15 is ok. It is to reduce delay for slow extruders. The required timer gets rounded down anyway, so it is never too high (except overflow).

minExtruderSpeed is not used, have removed it for next update.

**Comment by kyrreaa** [comment]
Sorry if my reply did not show up here.  Yes I have geared extruder with approx 1030 steps/mm.
As a result advance algo caused me significant issues before 0.92 and usually ended up with massive skipping and odd noises.
I have not tried with 0.92 as I have instead turned on advance in Sli3er 1.2.5 experimental and it seems to print better.
