### ISSUE TITLE
LCD rendering dissapears ocassionaly

### ISSUE THREAD

**Issue by mushketer888** [repetier/Repetier-Firmware#352]
Using Due+RADDS
Suddenly LCD data dissapears and doesnt render anything but menu keys are working
what can be the cause
communication also working

**Comment by repetier** [comment]
Depends on since when you have the problem. We have reduced some timings recently. but it worked on RADDS with normal delivered cable. Longer cable, crosstalk from WLAN, other cables can cause problems. I have also heard about defect cables.

Does it work when you enable printer and then at some time it starts getting wrong from time to time or does it keep disappeared?

**Comment by sigma957** [comment]
A while ago my LCD (RADDS v1.1) started to disappear after some time spent
in printing over USB. Recently I started to observe garbled characters as
well.

**Comment by repetier** [comment]
Garbled chars is a result of wrong signals coming to the display. Same might cause a command to disable lcd completely with bad luck. Big question is what causes the signals to get misunderstood knowing that the right signals leave the due. If you get garbled chars try moving the lcd cable around and see if it gets better to test if it's electric noise.

**Comment by mushketer888** [comment]
simga957, i have the same problem
when printing over usb after some time lcd dissappears

**Comment by mushketer888** [comment]
I think that it dissappears when heatears are on
When in dry run it works fine
Can anyone with this problem also check this?

**Comment by mushketer888** [comment]
Keys also stop to work...
So its a software error

**Comment by mushketer888** [comment]
Sometimes lcd dissapear when i just put usb cable IN or OUT...
