### ISSUE TITLE
Which vanilla Arduino boards is Repetier compatible with?

### ISSUE THREAD

**Issue by polkovnikov-ph** [repetier/Repetier-Firmware#446]
I'm planning to run Repetier on some of the official Arduino boards. I've read that Repetier is compatible with Melzi that uses atmega1284p, but I'm not proficient to compare it to Uno's ATmega328P or Mega's Atmega2560. Also there are possible corner cases, of which I'm unaware at all.

What's the size of the binary? Which common Arduino boards can handle RAM/ROM usage of this firmware and have proper clock frequency?

**Comment by jamesarm97** [comment]
Repetier is compatible with Melzi as all the wanhao i3's run it and I have compiled a few versions for it. Needs to disable all the non-usable parts like z probe and auto leveling. There are a few changes you will have to make if you are not using the versions I have posted since the melzi configuration seems broke in the newer version (at least the wanhao configuration). The common arduino board used is the Mega2560 but the Due is a better 32 but processor if you can go that route with the appropriate ramps type board (I am running the RADDS on my wanhao).

**Comment by repetier** [comment]
Nothing against the melzi board, but binary with all features is over 200KB so it won't fit. Practically all Arduiono AVR boards run 16MHz so speed is the same. Only due boards like RADDS with 32 bit are much faster. You can reduce memory usage be removing features to fit it on smaller boards, also I would not take anything below 128kb and vote for 256MB.
