### ISSUE TITLE
Scalable maximum speed for PWM part cooling fan

### ISSUE THREAD

**Issue by frazierjason** [repetier/Repetier-Firmware#590]
Please set this as a feature request issue.

I have a part fan (5015 blower) that gusts too strongly at 100 percent, and causes the hotend to rapidly cool and false detect as having a decoupled thermistor, killing the print.  I'd like to be able to set an artificial PWM limit for my part cooling fan(s).  If the part cooling fan's maximum PWM is 255, then I'd like to set the effective maximum PWM at 80, meaning a 50 percent fan speed is effectively 40 (not 127).  Can this be done?

**Comment by repetier** [comment]
The easy way would be to change the set fan speed method to multiply. But then it would also display 50% if reduction is 0.5 and you would need to convert it to float and then back or if you limit it to full percent you can do some integer math if value is in percent then. In total I don't think this is very useful and you can limit speed already in slicer configurations where the fan commands come from. There you can set max. fan speed. It is more fixing a problem introduced somewhere else, which is why I do not like that solution. Alternative solutions:
1. Fix fan to blow more to pla then to heater.
2. Increase temperature variance allowed for decoupling to not get decoupled message.
3. Modify slicer configuration to not use 100% fan.
